name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'

categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ðŸ“š Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "ðŸ”§ Maintenance"
    labels:
      - "chore"
      - "maintenance"
  - title: "â¬†ï¸ Dependencies"
    labels:
      - "dependencies"
      - "deps"

version-resolver:
  major:
    labels:
      - "breaking"
      - "breaking-change"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bugfix"
      - "bug"
      - "documentation"
      - "chore"
      - "maintenance"
      - "dependencies"
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
