coverage:
  status:
    project:
      default:
        target: auto    # maintain or improve coverage
        threshold: 2%   # allow up to 2% drop before failing
    patch:
      default:
        target: 80%     # new code in PRs must be at least 80% covered

comment:
  layout: "reach,diff,flags,files"
  behavior: default
