name: Draft Release

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            dry_run:
                description: "Dry run (do not publish the release)"
                required: false
                default: "false"
                type: choice
                options:
                    - "false"
                    - "true"

jobs:
    draft-release:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        permissions:
            contents: write
            pull-requests: read

        steps:
            - name: Create/Update Draft Release
              uses: release-drafter/release-drafter@v6
              with:
                  config-name: release-drafter.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-release:
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        permissions:
            contents: write
            pull-requests: read

        steps:
            - name: Publish Release
              uses: release-drafter/release-drafter@v6
              with:
                  config-name: release-drafter.yml
                  publish: ${{ github.event.inputs.dry_run == 'false' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
